### ISSUE TITLE
Error: `headers` should be a `Hash` but is a `Array`

### ISSUE THREAD

**Issue by derRobert** [appmail/appmail-php#3]
I had setup a postal installation. It works fine so far, but i am getting an error, when trying to send a message as described in your example:

```
[User Error] Uncaught AppMail\Error: [] `headers` should be a `Hash` but is a `Array`
GET /
Line 30 in [...]vendor/appmail/appmail/src/Client.php
```

Any ideas?

**Comment by adamcooke** [comment]
You should use the new postal-php rather than appmail-php. This bug is fixed in that one.

https://github.com/atech/postal-php
